# Set the pgvector columns to 384 dims for bge-small-en-v1.5 (the embedding
# service's default model, chosen to fit a small host). Embeddings can't be
# cast between dimensions, so they're cleared and regenerated by re-indexing.
class ChangeEmbeddingDimensionsTo384 < ActiveRecord::Migration[8.1]
  TABLES = {
    document_chunks: "index_document_chunks_on_embedding",
    headnotes: "index_headnotes_on_embedding",
  }.freeze

  def up
    TABLES.each { |table, index| set_dimension(table, index, 384) }
  end

  def down
    TABLES.each { |table, index| set_dimension(table, index, 1024) }
  end

  private

  def set_dimension(table, index_name, dim)
    execute "DROP INDEX IF EXISTS #{index_name}"
    execute "UPDATE #{table} SET embedding = NULL"
    execute "ALTER TABLE #{table} ALTER COLUMN embedding TYPE vector(#{dim})"
    execute <<~SQL
      CREATE INDEX #{index_name} ON #{table}
        USING hnsw (embedding vector_cosine_ops)
    SQL
  end
end
