# Widen the pgvector columns from 768 to 1024 dims for Qwen3-Embedding-0.6B.
# Existing embeddings can't be cast between dimensions, so they're cleared and
# regenerated by re-indexing (IndexDocumentJob / Search::Indexer).
class ChangeEmbeddingDimensionsTo1024 < ActiveRecord::Migration[8.1]
  TABLES = {
    document_chunks: "index_document_chunks_on_embedding",
    headnotes: "index_headnotes_on_embedding",
  }.freeze

  def up
    TABLES.each { |table, index| set_dimension(table, index, 1024) }
  end

  def down
    TABLES.each { |table, index| set_dimension(table, index, 768) }
  end

  private

  def set_dimension(table, index_name, dim)
    execute "DROP INDEX IF EXISTS #{index_name}"
    execute "UPDATE #{table} SET embedding = NULL"
    execute "ALTER TABLE #{table} ALTER COLUMN embedding TYPE vector(#{dim})"
    execute <<~SQL
      CREATE INDEX #{index_name} ON #{table}
        USING hnsw (embedding vector_cosine_ops)
    SQL
  end
end
